#!/bin/bash

set -x
set -e

cd $(dirname $0)

trap 'sudo kill -9 %1 %2' EXIT
cd ../../
adsf -p 3000 > adsf.log &
cd -
cd ../../server
sudo rm -rf server-state
sudo node nodejs-example.js > server.log &
cd -
cucumber $@
exit $?
