name: Release Drafter

on:
  push:
    branches:
      - master

# Permissions for default token (secrets.GITHUB_TOKEN)
permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@ed4bc48ec97379be2258e7b7ac2624a3e26ab809   # v7.4.0
        with:
          config-name: release-drafter.yml # the default, loads '.github/release-drafter.yml'
